n1 =float(input("fala um numero ai seu atoa:"))
n2 =float(input("fala um outro numero:"))
soma=(n1+n2)
subitracao=(n1-n2)
divisao=(n1/n2)
multiplique= (n1*n1)
print(soma)
print(subitracao)
print(divisao)
print(multiplique)