nota1 =float(input("digite sua nota do primeiro bimestre "))
print("essa merda de nota ",nota1, "e a sua")
nota2 =float(input("digite sua nota do segundo bimestre "))
print("que nota horrivel",nota2, "tente melhorar")
nota3 =float(input("digite sua nota do terceiro bimestre "))
print("quer uma dica? vai bater uma laje.",nota3," uma essa merda ")
nota4 =float(input("vc ja ta reprovado mesmo entao isso e so pra completar o ano "))
print("como eu disse",nota4, "vc ja reprovou mesmo")
soma = (nota1+nota2+nota3+nota4)
print("sua nota e ",soma, "ate o ano que vem sue burro")